# SPDX-FileCopyrightText: 2026 EfterScript contributors
# SPDX-License-Identifier: MIT

[package]
name = "xtask"
description = "cargo xtask automation for the EfterScript workspace"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ps-vm.workspace = true
